### ISSUE TITLE
The module name should be universal_versions.py  not the too generic versions.py 

### ISSUE THREAD

**Issue by pombredanne** [nexB/univers#1]
The module name should be universal_versions.py  not the too generic versions.py otherwise there will be namespace conflicts for sure

**Comment by sbs2001** [comment]
@pombredanne  I'm not sure universal-versions  is even a good name, provided we are doing things related to  version  ranges and their normalization.

How about calling this `vurl-toolkit` ?

**Comment by pombredanne** [comment]
I guess we settled on univers :) ... closing now!
