### ISSUE TITLE
fix GolangVersion version comparison

### ISSUE THREAD

**Issue by keshav-space** [nexB/univers#107]
`GolangVersion("v1.1.0")` is not raising InvalidVersion error leading to all sorts of problem

```python 
>>> from univers.versions import GolangVersion
>>> GolangVersion("v1.1.0") == GolangVersion("1.1.0")
False
```

**Comment by TG1999** [comment]
@keshav-space IMO the leading v is not a problem, actually the version comparison is the problem please checkout this branch https://github.com/TG1999/univers/tree/fix_comparison
```
>>> from univers.versions import *
>>> GolangVersion("v1.0") == GolangVersion("1.0")
True
```

**Comment by keshav-space** [comment]
> IMO the leading v is not a problem, actually the version comparison is the problem please checkout this branch https://github.com/TG1999/univers/tree/fix_comparison

Thanks @TG1999 it's working

**Comment by TG1999** [comment]
@keshav-space fix for this is merged in latest main now, closing this. feel free to reopen this if you have any more concerns re this issue
