### ISSUE TITLE
version string representation is missing type information

### ISSUE THREAD

**Issue by Hritik14** [nexB/univers#17]
```py
>>> from univers.versions import SemverVersion
>>> SemverVersion("2.0.0")
SemverVersion(string='2.0.0')
>>> str(SemverVersion("2.0.0"))
'2.0.0'
```
After converting a `Version` to string, it is impossible to switch back as the type (`SemverVersion`) information is lost. This will cause problems when saving and retrieving versions from a database.

One possible solution is to store the class name `SemverVersion` and the string representation both in the database.
Even so, would it make sense to have a vers like (but tiny) specification for versions ?
It could be something along the lines
```
ver:SemverVersion/2.0.0
```
I'm not even sure if this representation is required at all, comments please.

**Comment by pombredanne** [comment]
We have a versioning scheme which is tightly bound to a purl type or possibly specific to a single package (like sqlite or nginx) ... where would store a version outside of the context of a package type or versioning scheme?

I see  these cases:

- versions in a version range: they have a "vers" versioning scheme alright
- version(s) for a package: they are in the context of a package that has a purl `type`. The only case we may need to handle specifically is when a package does not use the default versioning scheme of its type but has a custom, specific one (say sqlite or nginx) in which case a versioning scheme attribute should be stored with the package, not with the version IMHO.

Would this make sense?

**Comment by Hritik14** [comment]
After today's call this makes sense to me.
