### ISSUE TITLE
Create new version range for "openssl"

### ISSUE THREAD

**Issue by pombredanne** [nexB/univers#36]
See https://www.openssl.org/policies/releasestrat.html

There are still old 1.1.1-style versions and these look like a lot PyPI.

**Comment by keshav-space** [comment]
For the base version `3.0` onward OpenSSL is using Semver
and for `1.1.1` they will continue with old versioning style ( 1.1.1 will be supported until 2023-09-11)

> Rest all other versions are no longer publicly supported


So, for openssl we will have two different versioning schema depending on the version ;(
>Imagine Something like this `vers:openssl/1.1.1k|3.0.2`

Only thing that seems good ->  https://www.openssl.org/news/vulnerabilities.xml

**Comment by pombredanne** [comment]
> So, for openssl we will have two different versioning schema depending on the version ;(

Yes! what I suggest as a design is this:
Something like a single OpensslVersion class that behaves differently if this is a 3 or an earlier version and once constructed track an internal version object that it delegates to:: either an old style version (string or some new LegacyOpensslVersion object)  or a Semver version object
