### ISSUE TITLE
Add support/tests for alpine ranges

### ISSUE THREAD

**Issue by pombredanne** [nexB/univers#37]
Thee are supposed to be mostly the same as gentoo, but we need to validate this. Having a vers scheme would make a lot of sense too in anycase

This file by @fabled https://git.alpinelinux.org/apk-tools/tree/tests/version.data contains all version tests from apk such as:
```
1.0 < 1.0bc		# invalid. do string sort
0.1.0_alpha = 0.1.0_alpha
0.1.0_alpha < 0.1.3_alpha
0.1.3_alpha > 0.1.0_alpha
```

We should validate we pass all these tests too.

**Comment by TG1999** [comment]
The current gentoo version comparison fails for this expression. this needs to be fixed for alpine and gentoo as well 

`006 > 1.0.0`

**Comment by pombredanne** [comment]
@TG1999 I think this is all merged now, correct?

**Comment by TG1999** [comment]
Yes @pombredanne , we can close this now
