### ISSUE TITLE
prerelease inside the build??

### ISSUE THREAD

**Issue by keshav-space** [nexB/univers#74]
https://github.com/nexB/univers/blob/6ad300ea515f99ffaae8b6a160724c32f027b5c0/tests/data/composer_gitlab.json#L1852-L1854

How did we end up with prerelease inside the build?
We are using Semver for Composer and `2.0.13+0alpha` isn't Semver.
Am I missing something?

**Comment by aalexanderr** [comment]
seems like a valid semver to me:
https://semver.org/

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
                ```

**Comment by keshav-space** [comment]
I know pre-release can have build, but can a build contain pre-release?

**Comment by aalexanderr** [comment]
I'm not sure I understand the question? Both release and  pre-release are types of builds - they are just marked in regards to lifecycle of releases.

**Comment by keshav-space** [comment]
> I'm not sure I understand the question? Both release and pre-release are types of builds - they are just marked in regards to lifecycle of releases.

I meant that according to semver specifications `<version core> "-" <pre-release> "+" <build>` is a valid semve-version but `<version core> "+" <build> "-" <pre-release> ` is not.

**Comment by keshav-space** [comment]
My bad `2.0.13+0alpha` is a valid semver version.
